### PR TITLE
FIX: use correct key for apam in exemplar also fix the ``ChainDB``

### PR DESCRIPTION
**Pull request by CJ-Wright**
key error message

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This passes tests on my local.

**Comment by sbillinge** [comment]
thanks Chris

**Comment by sbillinge** [comment]
@CJ-Wright please could you run bootstrap on this again and PR the result into by branch. Then I think this will be ready to be pulled in.

I want to make a few tweaks to the presentation list, but they can be done in a different branch.  I will put up issues for those.

**Comment by CJ-Wright** [comment]
sure

**Comment by sbillinge** [comment]
this suggests to me that (a) we are going to have to validate database
entries quite a bit (and against builders) at commit time and (b) when we
do that, give as much useful info back to the users about why their new db
entry didn't validate, or risk being killed by frustrated grad students.....

I am clearly not even able to create valid db entries in the schema, so
there is little hope that this will work on a larger scale without this...

**Pull request merged**
